// AUTO-GÉNÉRÉ par backend/scripts/generate-embedded-thumbs.ts — NE PAS ÉDITER.
// Vignettes statiques du pack embarqué (ROADMAP 2.1). React Native exige des
// chemins require() littéraux pour bundler un asset : cet index les fournit.
// Clé = exercises.external_id ; valeur = module asset (numérique RN).

export const EMBEDDED_EXERCISE_IMAGES: Record<string, number> = {
  "3_4_Sit-Up": require("./3_4_Sit-Up.webp"),
  "Barbell_Curl": require("./Barbell_Curl.webp"),
  "Barbell_Seated_Calf_Raise": require("./Barbell_Seated_Calf_Raise.webp"),
  "Barbell_Squat": require("./Barbell_Squat.webp"),
  "Bench_Dips": require("./Bench_Dips.webp"),
  "Chin-Up": require("./Chin-Up.webp"),
  "Clean": require("./Clean.webp"),
  "Clean_Deadlift": require("./Clean_Deadlift.webp"),
  "Close-Grip_Barbell_Bench_Press": require("./Close-Grip_Barbell_Bench_Press.webp"),
  "Close-Grip_Dumbbell_Press": require("./Close-Grip_Dumbbell_Press.webp"),
  "Concentration_Curls": require("./Concentration_Curls.webp"),
  "Crunches": require("./Crunches.webp"),
  "Decline_Push-Up": require("./Decline_Push-Up.webp"),
  "Dumbbell_Bench_Press": require("./Dumbbell_Bench_Press.webp"),
  "Dumbbell_Bicep_Curl": require("./Dumbbell_Bicep_Curl.webp"),
  "Dumbbell_Flyes": require("./Dumbbell_Flyes.webp"),
  "Dumbbell_Incline_Row": require("./Dumbbell_Incline_Row.webp"),
  "Dumbbell_Lunges": require("./Dumbbell_Lunges.webp"),
  "Dumbbell_Raise": require("./Dumbbell_Raise.webp"),
  "Dumbbell_Seated_One-Leg_Calf_Raise": require("./Dumbbell_Seated_One-Leg_Calf_Raise.webp"),
  "Dumbbell_Squat": require("./Dumbbell_Squat.webp"),
  "Glute_Kickback": require("./Glute_Kickback.webp"),
  "Good_Morning": require("./Good_Morning.webp"),
  "Hammer_Curls": require("./Hammer_Curls.webp"),
  "Incline_Hammer_Curls": require("./Incline_Hammer_Curls.webp"),
  "Incline_Push-Up": require("./Incline_Push-Up.webp"),
  "Incline_Push-Up_Close-Grip": require("./Incline_Push-Up_Close-Grip.webp"),
  "Inverted_Row": require("./Inverted_Row.webp"),
  "Leg_Lift": require("./Leg_Lift.webp"),
  "Oblique_Crunches": require("./Oblique_Crunches.webp"),
  "One-Arm_Dumbbell_Row": require("./One-Arm_Dumbbell_Row.webp"),
  "Plank": require("./Plank.webp"),
  "Preacher_Curl": require("./Preacher_Curl.webp"),
  "Pullups": require("./Pullups.webp"),
  "Push-Up_Wide": require("./Push-Up_Wide.webp"),
  "Pushups": require("./Pushups.webp"),
  "Reverse_Crunch": require("./Reverse_Crunch.webp"),
  "Reverse_Flyes": require("./Reverse_Flyes.webp"),
  "Seated_Dumbbell_Press": require("./Seated_Dumbbell_Press.webp"),
  "Seated_Triceps_Press": require("./Seated_Triceps_Press.webp"),
  "Single_Dumbbell_Raise": require("./Single_Dumbbell_Raise.webp"),
  "Single_Leg_Glute_Bridge": require("./Single_Leg_Glute_Bridge.webp"),
  "Sit-Up": require("./Sit-Up.webp"),
  "Split_Squat_with_Dumbbells": require("./Split_Squat_with_Dumbbells.webp"),
  "Standing_Barbell_Calf_Raise": require("./Standing_Barbell_Calf_Raise.webp"),
  "Standing_Dumbbell_Press": require("./Standing_Dumbbell_Press.webp"),
  "Standing_Military_Press": require("./Standing_Military_Press.webp"),
  "Sumo_Deadlift": require("./Sumo_Deadlift.webp"),
  "Tricep_Dumbbell_Kickback": require("./Tricep_Dumbbell_Kickback.webp"),
  "V-Bar_Pullup": require("./V-Bar_Pullup.webp"),
};
