-- Migration ROADMAP 2.1 — relecture humaine des noms FR (DATA_MODEL.md §2.3).
-- Corrige/valide manuellement les traductions FR generees best-effort par
-- l'import (backend/scripts/import-exercises.ts) — porte le compteur
-- needs_review a 0 dans le rapport d'import.
--
-- ⚠️ Fichier RECONSTITUE (2026-07-25) : cette migration avait ete appliquee
-- au projet Supabase distant via le MCP (version 20260723195534) sans qu'un
-- fichier local n'existe dans supabase/migrations/. Reconstituee ici a
-- l'identique depuis supabase_migrations.schema_migrations pour respecter la
-- regle "source de verite = migrations SQL manuelles" (DATA_MODEL.md §4).
update public.exercises e set name_fr = v.name_fr
from (values
  ('3_4_Sit-Up', 'Relevé de buste 3/4'),
  ('Ab_Crunch_Machine', 'Crunch à la machine'),
  ('Barbell_Ab_Rollout', 'Rollout abdominal à la barre'),
  ('Barbell_Rollout_from_Bench', 'Rollout à la barre depuis un banc'),
  ('Barbell_Side_Bend', 'Flexion latérale à la barre'),
  ('Cable_Crunch', 'Crunch à la poulie'),
  ('Cable_Reverse_Crunch', 'Crunch inversé à la poulie'),
  ('Cable_Russian_Twists', 'Rotation russe à la poulie'),
  ('Cable_Seated_Crunch', 'Crunch assis à la poulie'),
  ('Crunches', 'Crunch'),
  ('Decline_Oblique_Crunch', 'Crunch oblique décliné'),
  ('Decline_Reverse_Crunch', 'Crunch inversé décliné'),
  ('Dumbbell_Side_Bend', 'Flexion latérale à l''haltère'),
  ('Exercise_Ball_Crunch', 'Crunch sur swiss ball'),
  ('Flat_Bench_Lying_Leg_Raise', 'Relevé de jambes allongé sur banc plat'),
  ('Kettlebell_Windmill', 'Moulinet à la kettlebell'),
  ('Oblique_Crunches', 'Crunch oblique'),
  ('Plank', 'Gainage'),
  ('Plate_Twist', 'Rotation avec disque'),
  ('Press_Sit-Up', 'Redressement assis avec développé'),
  ('Reverse_Crunch', 'Crunch inversé'),
  ('Seated_Barbell_Twist', 'Rotation assise à la barre'),
  ('Sit-Up', 'Redressement assis'),
  ('Smith_Machine_Hip_Raise', 'Élévation de bassin à la machine Smith'),
  ('Weighted_Crunches', 'Crunch lesté'),
  ('Monster_Walk', 'Marche latérale avec élastique'),
  ('Thigh_Abductor', 'Abducteurs à la machine'),
  ('Band_Hip_Adductions', 'Adduction de hanche à l''élastique'),
  ('Thigh_Adductor', 'Adducteurs à la machine'),
  ('Alternate_Hammer_Curl', 'Curl marteau en alternance'),
  ('Barbell_Curl', 'Curl à la barre'),
  ('Cable_Preacher_Curl', 'Curl pupitre à la poulie'),
  ('Close-Grip_EZ-Bar_Curl_with_Band', 'Curl prise serrée à la barre EZ avec élastique'),
  ('Concentration_Curls', 'Curl concentré'),
  ('Dumbbell_Bicep_Curl', 'Curl biceps à l''haltère'),
  ('EZ-Bar_Curl', 'Curl à la barre EZ'),
  ('Hammer_Curls', 'Curl marteau'),
  ('Incline_Hammer_Curls', 'Curl marteau incliné'),
  ('Machine_Bicep_Curl', 'Curl biceps à la machine'),
  ('Machine_Preacher_Curls', 'Curl pupitre à la machine'),
  ('Preacher_Curl', 'Curl pupitre'),
  ('Reverse_Barbell_Curl', 'Curl inversé à la barre'),
  ('Reverse_Cable_Curl', 'Curl inversé à la poulie'),
  ('Reverse_Plate_Curls', 'Curl inversé avec disque'),
  ('Seated_Dumbbell_Curl', 'Curl assis à l''haltère'),
  ('Standing_Biceps_Cable_Curl', 'Curl biceps debout à la poulie'),
  ('Wide-Grip_Standing_Barbell_Curl', 'Curl debout prise large à la barre'),
  ('Balance_Board', 'Planche d''équilibre'),
  ('Barbell_Seated_Calf_Raise', 'Élévation mollets assise à la barre'),
  ('Calf_Press', 'Presse mollets'),
  ('Calf_Raise_On_A_Dumbbell', 'Élévation mollets sur haltère'),
  ('Dumbbell_Seated_One-Leg_Calf_Raise', 'Élévation mollets assise unilatérale à l''haltère'),
  ('Seated_Calf_Raise', 'Élévation mollets assise'),
  ('Standing_Barbell_Calf_Raise', 'Élévation mollets debout à la barre'),
  ('Standing_Calf_Raises', 'Élévation mollets debout'),
  ('Standing_Dumbbell_Calf_Raise', 'Élévation mollets debout à l''haltère'),
  ('Alternating_Floor_Press', 'Développé au sol en alternance'),
  ('Cable_Chest_Press', 'Développé pectoraux à la poulie'),
  ('Cable_Crossover', 'Écarté croisé à la poulie'),
  ('Decline_Dumbbell_Flyes', 'Écarté décliné à l''haltère'),
  ('Decline_Push-Up', 'Pompe déclinée'),
  ('Dumbbell_Bench_Press', 'Développé couché à l''haltère'),
  ('Dumbbell_Flyes', 'Écarté à l''haltère'),
  ('Front_Raise_And_Pullover', 'Élévation frontale et pull-over'),
  ('Incline_Cable_Chest_Press', 'Développé pectoraux incliné à la poulie'),
  ('Incline_Dumbbell_Flyes', 'Écarté incliné à l''haltère'),
  ('Incline_Dumbbell_Press', 'Développé incliné à l''haltère'),
  ('Incline_Push-Up', 'Pompe inclinée'),
  ('Incline_Push-Up_Wide', 'Pompe inclinée prise large'),
  ('Machine_Bench_Press', 'Développé couché à la machine'),
  ('Push-Up_Wide', 'Pompe prise large'),
  ('Pushups', 'Pompe'),
  ('Smith_Machine_Bench_Press', 'Développé couché à la machine Smith'),
  ('Cable_Wrist_Curl', 'Curl de poignet à la poulie'),
  ('Finger_Curls', 'Curl des doigts'),
  ('Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench', 'Curl de poignet aux haltères, paumes vers le haut, sur banc'),
  ('Seated_Dumbbell_Palms-Down_Wrist_Curl', 'Curl de poignet assis aux haltères, paumes vers le bas'),
  ('Seated_Dumbbell_Palms-Up_Wrist_Curl', 'Curl de poignet assis aux haltères, paumes vers le haut'),
  ('Seated_Palm-Up_Barbell_Wrist_Curl', 'Curl de poignet assis à la barre, paumes vers le haut'),
  ('Standing_Olympic_Plate_Hand_Squeeze', 'Serrage de disque olympique debout'),
  ('Wrist_Roller', 'Enrouleur de poignet'),
  ('Wrist_Rotations_with_Straight_Bar', 'Rotation de poignet à la barre droite'),
  ('Barbell_Glute_Bridge', 'Pont fessier à la barre'),
  ('Barbell_Hip_Thrust', 'Hip thrust à la barre'),
  ('Glute_Kickback', 'Kickback fessier'),
  ('Hip_Extension_with_Bands', 'Extension de hanche à l''élastique'),
  ('Kneeling_Squat', 'Squat à genoux'),
  ('Leg_Lift', 'Levée de jambe'),
  ('Pull_Through', 'Pull-through à la poulie'),
  ('Single_Leg_Glute_Bridge', 'Pont fessier unilatéral'),
  ('Ball_Leg_Curl', 'Leg curl sur swiss ball'),
  ('Band_Good_Morning', 'Good morning à l''élastique'),
  ('Clean', 'Épaulé'),
  ('Clean_Deadlift', 'Soulevé de terre épaulé'),
  ('Dumbbell_Clean', 'Épaulé à l''haltère'),
  ('Good_Morning', 'Good morning'),
  ('Lying_Leg_Curls', 'Leg curl allongé'),
  ('One-Arm_Kettlebell_Clean', 'Épaulé à la kettlebell à un bras'),
  ('One-Arm_Kettlebell_Swings', 'Swing à la kettlebell à un bras'),
  ('Seated_Band_Hamstring_Curl', 'Curl ischio-jambiers assis à l''élastique'),
  ('Seated_Leg_Curl', 'Leg curl assis'),
  ('Smith_Machine_Stiff-Legged_Deadlift', 'Soulevé de terre jambes tendues à la machine Smith'),
  ('Snatch_Deadlift', 'Soulevé de terre arraché'),
  ('Standing_Leg_Curl', 'Leg curl debout'),
  ('Sumo_Deadlift', 'Soulevé de terre sumo'),
  ('Band_Assisted_Pull-Up', 'Traction assistée à l''élastique'),
  ('Chin-Up', 'Traction prise supination'),
  ('Leverage_Iso_Row', 'Rowing iso à la machine à levier'),
  ('Muscle_Up', 'Muscle-up'),
  ('One_Arm_Lat_Pulldown', 'Tirage vertical à un bras'),
  ('Pullups', 'Traction'),
  ('Shotgun_Row', 'Rowing unilatéral à la poulie'),
  ('Straight-Arm_Pulldown', 'Tirage bras tendus à la poulie'),
  ('V-Bar_Pullup', 'Traction prise serrée en V'),
  ('Weighted_Pull_Ups', 'Traction lestée'),
  ('Wide-Grip_Lat_Pulldown', 'Tirage vertical prise large'),
  ('Barbell_Deadlift', 'Soulevé de terre à la barre'),
  ('Deadlift_with_Bands', 'Soulevé de terre avec élastique'),
  ('Deadlift_with_Chains', 'Soulevé de terre avec chaînes'),
  ('Hyperextensions_Back_Extensions', 'Hyperextensions lombaires'),
  ('Hyperextensions_With_No_Hyperextension_Bench', 'Hyperextensions lombaires sans banc'),
  ('Reverse_Band_Deadlift', 'Soulevé de terre avec élastique inversé'),
  ('Seated_Good_Mornings', 'Good morning assis'),
  ('Weighted_Ball_Hyperextension', 'Hyperextension lestée sur swiss ball'),
  ('Alternating_Kettlebell_Row', 'Rowing à la kettlebell en alternance'),
  ('Dumbbell_Incline_Row', 'Rowing incliné à l''haltère'),
  ('Inverted_Row', 'Rowing inversé au poids du corps'),
  ('Leverage_High_Row', 'Rowing haut à la machine à levier'),
  ('One_Arm_Chin-Up', 'Traction à un bras'),
  ('One-Arm_Dumbbell_Row', 'Rowing à un bras à l''haltère'),
  ('One-Arm_Kettlebell_Row', 'Rowing à un bras à la kettlebell'),
  ('Reverse_Grip_Bent-Over_Rows', 'Rowing buste penché prise inversée'),
  ('Seated_Cable_Rows', 'Rowing assis à la poulie'),
  ('Sled_Row', 'Rowing au traîneau'),
  ('Smith_Machine_Bent_Over_Row', 'Rowing buste penché à la machine Smith'),
  ('Suspended_Row', 'Rowing suspendu'),
  ('Isometric_Neck_Exercise_-_Front_And_Back', 'Exercice isométrique de nuque, avant/arrière'),
  ('Isometric_Neck_Exercise_-_Sides', 'Exercice isométrique de nuque, latéral'),
  ('Lying_Face_Down_Plate_Neck_Resistance', 'Résistance de nuque avec disque, allongé face contre banc'),
  ('Lying_Face_Up_Plate_Neck_Resistance', 'Résistance de nuque avec disque, allongé sur le dos'),
  ('Seated_Head_Harness_Neck_Resistance', 'Résistance de nuque au harnais, assis'),
  ('Barbell_Squat', 'Squat à la barre'),
  ('Cable_Deadlifts', 'Soulevé de terre à la poulie'),
  ('Dumbbell_Lunges', 'Fentes à l''haltère'),
  ('Dumbbell_Squat', 'Squat à l''haltère'),
  ('Goblet_Squat', 'Squat goblet'),
  ('Hack_Squat', 'Squat hack'),
  ('Hip_Flexion_with_Band', 'Flexion de hanche à l''élastique'),
  ('Leg_Extensions', 'Leg extension'),
  ('Leg_Press', 'Presse à cuisses'),
  ('Single-Leg_Leg_Extension', 'Leg extension unilatérale'),
  ('Smith_Machine_Squat', 'Squat à la machine Smith'),
  ('Split_Squat_with_Dumbbells', 'Fente bulgare avec haltères'),
  ('Trap_Bar_Deadlift', 'Soulevé de terre à la barre hexagonale'),
  ('Alternating_Cable_Shoulder_Press', 'Développé épaules à la poulie en alternance'),
  ('Alternating_Deltoid_Raise', 'Élévation deltoïdes en alternance'),
  ('Alternating_Kettlebell_Press', 'Développé à la kettlebell en alternance'),
  ('Band_Pull_Apart', 'Écarté à l''élastique'),
  ('Barbell_Incline_Shoulder_Raise', 'Élévation épaules inclinée à la barre'),
  ('Barbell_Shoulder_Press', 'Développé épaules à la barre'),
  ('Cable_Seated_Lateral_Raise', 'Élévation latérale assise à la poulie'),
  ('Cable_Shoulder_Press', 'Développé épaules à la poulie'),
  ('Clean_and_Press', 'Épaulé-développé'),
  ('Dumbbell_Incline_Shoulder_Raise', 'Élévation épaules inclinée à l''haltère'),
  ('Dumbbell_Raise', 'Élévation à l''haltère'),
  ('Face_Pull', 'Face pull'),
  ('Kettlebell_Seated_Press', 'Développé assis à la kettlebell'),
  ('One-Arm_Incline_Lateral_Raise', 'Élévation latérale inclinée à un bras'),
  ('One-Arm_Kettlebell_Jerk', 'Jeté à la kettlebell à un bras'),
  ('Reverse_Flyes', 'Écarté inversé'),
  ('Reverse_Machine_Flyes', 'Écarté inversé à la machine'),
  ('Seated_Cable_Shoulder_Press', 'Développé épaules assis à la poulie'),
  ('Seated_Dumbbell_Press', 'Développé épaules assis à l''haltère'),
  ('Single_Dumbbell_Raise', 'Élévation unilatérale à l''haltère'),
  ('Smith_Incline_Shoulder_Raise', 'Élévation épaules inclinée à la machine Smith'),
  ('Smith_Machine_One-Arm_Upright_Row', 'Rowing menton à un bras à la machine Smith'),
  ('Standing_Alternating_Dumbbell_Press', 'Développé épaules debout en alternance à l''haltère'),
  ('Standing_Dumbbell_Press', 'Développé épaules debout à l''haltère'),
  ('Standing_Military_Press', 'Développé militaire debout'),
  ('Barbell_Shrug', 'Haussement d''épaules à la barre'),
  ('Barbell_Shrug_Behind_The_Back', 'Haussement d''épaules derrière le dos à la barre'),
  ('Cable_Shrugs', 'Haussement d''épaules à la poulie'),
  ('Calf-Machine_Shoulder_Shrug', 'Haussement d''épaules à la machine à mollets'),
  ('Clean_Shrug', 'Haussement d''épaules épaulé'),
  ('Dumbbell_Shrug', 'Haussement d''épaules à l''haltère'),
  ('Smith_Machine_Upright_Row', 'Rowing menton à la machine Smith'),
  ('Standing_Dumbbell_Upright_Row', 'Rowing menton debout à l''haltère'),
  ('Band_Skull_Crusher', 'Extension triceps au sol à l''élastique'),
  ('Bench_Dips', 'Dips sur banc'),
  ('Cable_Incline_Triceps_Extension', 'Extension triceps inclinée à la poulie'),
  ('Cable_Lying_Triceps_Extension', 'Extension triceps allongée à la poulie'),
  ('Cable_One_Arm_Tricep_Extension', 'Extension triceps à un bras à la poulie'),
  ('Close-Grip_Barbell_Bench_Press', 'Développé couché prise serrée à la barre'),
  ('Close-Grip_Dumbbell_Press', 'Développé prise serrée à l''haltère'),
  ('Close-Grip_EZ-Bar_Press', 'Développé prise serrée à la barre EZ'),
  ('Dip_Machine', 'Dips à la machine'),
  ('Incline_Push-Up_Close-Grip', 'Pompe inclinée prise serrée'),
  ('Machine_Triceps_Extension', 'Extension triceps à la machine'),
  ('Seated_Triceps_Press', 'Développé triceps assis'),
  ('Tricep_Dumbbell_Kickback', 'Kickback triceps à l''haltère')
) as v(external_id, name_fr)
where e.external_id = v.external_id;
